### ISSUE TITLE
Add most popular languages bar chart (about section)

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/open-source#10]
![image](https://user-images.githubusercontent.com/5460365/80823873-60ec7880-8bab-11ea-8191-95884497cae3.png)

**Comment by LeonelSantiago** [comment]
I think you could rename this to something like Add most popular languages bar chart. Because with a charts library usually you don't need to make the calculations.

**Comment by DannyFeliz** [comment]
For sure, but you also will need to organize the data to make it presentable in a chart.

**Comment by LeonelSantiago** [comment]
Sure, you're right. That have to be done. Thank you for consider my suggestion.

**Comment by DannyFeliz** [comment]
Done #31
