### ISSUE TITLE
Calculate developers stats (about section)

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/open-source#11]
With all the data from [repos](developersdo.github.io/opensource/data/repos.json) and [user](developersdo.github.io/opensource/data/users.json)

1. Get a total of developers and how many of them have more than 10 repositories.

2. Get a total of repositories and the average of repositories of each user. Also get all repositories with more than 1 star.

3. We need to extract all the programming languages used across all repositories.

![image](https://user-images.githubusercontent.com/5460365/80824051-ad37b880-8bab-11ea-923a-d05ab24653b3.png)

**Comment by vyzaldysanchez** [comment]
Any more details you may want to let us know about?

**Comment by DannyFeliz** [comment]
@vyzaldysanchez Done, let me know if you need more details.
