### ISSUE TITLE
Add hamberguer menu

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/open-source#12]
We should hide the menu and show a hamburger menu on mobile
![image](https://user-images.githubusercontent.com/5460365/80824271-15869a00-8bac-11ea-89d6-a1526ed82f7d.png)

**Comment by LeonelSantiago** [comment]
@DannyFeliz hey man, I'm trying to assign me this issue and I think I can't because I'm not part of the organization. Could you invite me please?

**Comment by DannyFeliz** [comment]
@LeonelSantiago Done, check your email.

**Comment by LeonelSantiago** [comment]
Great! Thank you man.
