### ISSUE TITLE
Update the opensource data

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/open-source#39]
We need to update the source where we get the data; we should start using [opensource-data](https://developersdo.github.io/opensource-data/)

We should change the source here: https://github.com/VueDominicana/open-source/blob/master/src/util/api.js#L3

Considerations with this source:
- The data is not sorted, we need to sort it by ourself
- It doesn't have the `position` key
- It doesn't have the `forked` key

**Comment by ljcordero** [comment]
For the `forked` key and also for the count of repositories of a developer, may us after fetch the data call a action that change the developers state with a calculated value ?
