### ISSUE TITLE
Add search bar on the repository and developer section (HTML only)

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/open-source#8]
![image](https://user-images.githubusercontent.com/5460365/80823485-b8d6af80-8baa-11ea-8d84-a99aec2c84d9.png)

**Comment by joseaquino5** [comment]
I'll take this one!

**Comment by LeonelSantiago** [comment]
@DannyFeliz  Considering this is going to be in two different views, even though it should be the same component, shouldn't be this two different issues?

**Comment by DannyFeliz** [comment]
> @DannyFeliz  Considering this is going to be in two different views, even though it should be the same component, shouldn't be this two different issues?

@LeonelSantiago since we're going to reuse it as a component I don't think it is necessary to create another issue just for that, so let keep just one.

**Comment by LeonelSantiago** [comment]
> > @DannyFeliz  Considering this is going to be in two different views, even though it should be the same component, shouldn't be this two different issues?
> 
> @LeonelSantiago since we're going to reuse it as a component I don't think it is necessary to create another issue just for that, so let keep just one.

Fine. Sounds good to me.

**Comment by DannyFeliz** [comment]
Done #35
